apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "canary-testing.fullname" . }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}