apiVersion: v1
kind: Service
metadata:
  name: {{ include "canary-testing.fullname" . }}
  labels:
    {{- include "canary-testing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "canary-testing.selectorLabels" . | nindent 4 }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "canary-testing.fullname" . }}
spec:
  hosts:
  {{- range .Values.ingress.hosts }}
   - {{ .host }}
  {{- end }}
  gateways:
  - {{ include "canary-testing.fullname" . }}
  http:
    {{- if eq .Values.image.tag .Values.image.canaryTag }}
    {{- else }}
    - name: "canary-route"
      match:
        - headers:
            release:
              exact: "canary"
      route:
      - destination:
          host: {{ include "canary-testing.fullname" . }}
          subset: canary
    {{- end }}
    - name: "Production Route"
      route:
        - destination:
            host: {{ include "canary-testing.fullname" . }}
            subset: production